### ISSUE TITLE
Serial polling into v4

### ISSUE THREAD

**Issue by drenda** [tdelenikas/smslib#12]
Hi,
unfortunately some modems had the timeout problem with RxTx: http://smslib.org/doc/smslib/troubleshooting/.
I don't see the polling implementation in v4. There is a workaround for this?

Thanks

**Comment by tdelenikas** [comment]
Hi,

This version always use polling. Something else must be wrong in your case...

Are you using a standard serial port or a usb connection? What modem are you using?

It could be the flow control. Edit SerialModemDriver.java, notice the commented-out lines: 49~51. You could try different combinations of flow control to see if it works.

If anything works, let me know in order to try and add it in base code.

**Comment by drenda** [comment]
Hi,
I'm using a Raspberry + an usb modem Wavecom M1306B Q2403 that is a supported smslib modem.
I'm using RXTX 2.2pre2-11.

Seems the problem happens when I put many sms in the queue of the modem (let's say 100-150) and the modem starts to send them.
At some point the sms starts to became failed "noRoute". Today, when it happens again I put here the stack trace of the exception.

I seen commented-out lines. So do you suggest to enable flowcontrol IN_OUT? I should clone the repository, make these changes and then create my custom jar of smslib?

Thanks

**Comment by tdelenikas** [comment]
Hi,

If things are like you describe, the is no point messing around with flow control. Your modem works ok up to some moment in time. If there was a flowcontrol problem, you wouldn't connect at all.

When you face the NoRoute error, does your modem get reset or something (by SMSLib, I mean)? Or from then on, everything fails?

**Comment by drenda** [comment]
Hi tdelenikas and thanks for your quick reply. Unfortunately I had some problems in logj -> log4j2 bridge so I lost smslib debug logs in the past. Now I fixed all and I'm waiting the problem appears again. I think in some days I will see again the problem (I hope). Thanks

**Comment by drenda** [comment]
Hi tdelenikas, finally I've logs! There are a bit verbose, so here http://pastie.org/private/w2l1nbd6uyrzdniwpgyvg you can see the logs.

This what happens:
1. many sms sent successfully
2. at some point I've a GatewayMessageDispatcher:52-Send failed!
1. then I've a Timeout elapsed for /dev/ttyUSB0:115200
2. all folllowing sms fails with "noroute" error
3. at the end I stopped the application

I hope this logs helps to understand the problem. Thanks

Hi tdelenikas, finally I've logs! There are a bit verbose, so I attach the file.
This what happens:
1. many sms sent successfully
2. at some point I've a GatewayMessageDispatcher:52-Send failed!
3. then I've a Timeout elapsed for /dev/ttyUSB0:115200
4. all folllowing sms fails with "noroute" error
5. at the end I stopped the application

I hope this logs helps to understand the problem. Thanks

**Comment by drenda** [comment]
Hi, someone have some ideas about? Thanks

**Comment by tdelenikas** [comment]
Hi,

1) I assume that when you restart smslib, everything works ok right?
2) Have you tried lowering your baud rate? Is it more or less stable?
3) How many sms do you send before this issue appears? You say "many". How many? 10? 1000?

The strange thing here is that although the modem (or the link) seems to be in a "strange" state, throwing errors and timeouts, you still get notifications back from the modem:

```
05/10/2015 12:30:51,863 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CMTI: "SM",8
```

**Comment by drenda** [comment]
Hi,
1) exactly
2) It will not work because:

WARNING:  RXTX Version mismatch
        Jar version = RXTX-2.2pre1
        native lib Version = RXTX-2.2pre2
====== Found port: /dev/ttyUSB0

> > Trying at   9600...No device...
> > Trying at  14400...No device... (Invalid Parameter)
> > Trying at  19200...No device...
> > Trying at  28800...No device... (Invalid Parameter)
> > Trying at  33600...No device... (Invalid Parameter)
> > Trying at  38400...No device... (Invalid Parameter)
> > Trying at  56000...No device... (Invalid Parameter)
> > Trying at  57600...No device...
> > Trying at 115200...  Getting Info... Found: AT+CGMM MULTIBAND  900E  1800

Infact tried with values <115200 I've always a communication timeout.

3)Depends. Let's say 100/200

Yes it's strange what you pointed out!

2015-10-21 7:51 GMT+02:00 Thanasis Delenikas notifications@github.com:

> Hi,
> 
> 1) I assume that when you restart smslib, everything works ok right?
> 2) Have you tried lowering your baud rate? Is it more or less stable?
> 3) How many sms do you send before this issue appears? You say "many". How
> many? 10? 1000?
> 
> The strange thing here is that although the modem (or the link) seems to
> be in a "strange" state, throwing errors and timeouts, you still get
> notifications back from the modem:
> 
> 05/10/2015 12:30:51,863 DEBUG Thread-27 AbstractModemDriver:129-/dev/ttyUSB0:115200 >>> +CMTI: "SM",8
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/smslib/smslib/issues/12#issuecomment-149790563.

## 

Daniele Renda

**Comment by tdelenikas** [comment]
Several GSM modems require specific baud rates to work. It's not strange that your modem requires 115K+ to work.

I have no answer for the main issue you are facing... Could be an overload or something, I am not sure.

**Comment by drenda** [comment]
I agree, I think it's an overload. There is a way in smslib to limit the
rate of sms in/out?

Thanks

2015-12-17 17:45 GMT+01:00 Thanasis Delenikas notifications@github.com:

> Several GSM modems require specific baud rates to work. It's not strange
> that your modem requires 115K+ to work.
> 
> I have no answer for the main issue you are facing... Could be an overload
> or something, I am not sure.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/smslib/smslib/issues/12#issuecomment-165505926.

## 

Daniele Renda

**Comment by tdelenikas** [comment]
Try adding something like this in your code:

```
Settings.gatewayDispatcherYield = 1000;
```

The value (1000) is milliseconds and it will delay each outbound message by this value.

**Comment by drenda** [comment]
I'll try, thanks

2015-12-17 18:32 GMT+01:00 Thanasis Delenikas notifications@github.com:

> Try adding something like this in your code:
> 
> Settings.gatewayDispatcherYield = 1000;
> 
> The value (1000) is milliseconds and it will delay each outbound message
> by this value.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/smslib/smslib/issues/12#issuecomment-165522682.

## 

Daniele Renda
